import type { SlideshowPhoto } from "./types";

export const SLIDESHOW_PHOTOS: SlideshowPhoto[] = [
  {
    image: "/images/about/daytona.jpg",
    alt: "Daytona Beach",
    width: 1483,
    height: 1977,
    place: "Daytona, FL",
    date: "May, 2026",
  },
  {
    image: "/images/about/boston.png",
    alt: "Boston",
    width: 1168,
    height: 1556,
    place: "Boston, MA",
    date: "August, 2025",
  },
  {
    image: "/images/about/providence.png",
    alt: "Providence",
    width: 1166,
    height: 1556,
    place: "Providence, RI",
    date: "August, 2025",
  },
  {
    image: "/images/about/vietnam.png",
    alt: "Vietnam",
    width: 1166,
    height: 1556,
    place: "Ho Chi Minh, Vietnam",
    date: "April, 2025",
  },
  {
    image: "/images/about/bali.png",
    alt: "Bali",
    width: 1168,
    height: 1556,
    place: "Bali, Indonesia",
    date: "March, 2025",
  },
  {
    image: "/images/about/penang.png",
    alt: "Penang",
    width: 1166,
    height: 1556,
    place: "Penang, Malaysia",
    date: "March, 2025",
  },
  {
    image: "/images/about/tokyo.png",
    alt: "Tokyo",
    width: 1168,
    height: 1556,
    place: "Tokyo, Japan",
    date: "March, 2025",
  },
  {
    image: "/images/about/kyoto.png",
    alt: "Kyoto",
    width: 1168,
    height: 1556,
    place: "Kyoto, Japan",
    date: "March, 2025",
  },
  {
    image: "/images/about/nara.png",
    alt: "Nara",
    width: 1168,
    height: 1556,
    place: "Nara, Japan",
    date: "March, 2025",
  },
  {
    image: "/images/about/singapore.png",
    alt: "Singapore",
    width: 1168,
    height: 1556,
    place: "Singapore",
    date: "February, 2025",
  },
  {
    image: "/images/about/tai-o.png",
    alt: "Tai O, Hong Kong",
    width: 1168,
    height: 1556,
    place: "Tai O, Hong Kong",
    date: "January, 2025",
  },
  {
    image: "/images/about/kowloon.png",
    alt: "Kowloon",
    width: 1168,
    height: 1556,
    place: "Kowloon, Hong Kong",
    date: "January, 2025",
  },
  {
    image: "/images/about/macao.png",
    alt: "Macao",
    width: 1168,
    height: 1556,
    place: "Macao",
    date: "January, 2025",
  },
  {
    image: "/images/about/alishan.png",
    alt: "Alishan",
    width: 1168,
    height: 1556,
    place: "Alishan, Taiwan",
    date: "January, 2025",
  },
  {
    image: "/images/about/taipei.png",
    alt: "Taipei",
    width: 1168,
    height: 1556,
    place: "Taipei, Taiwan",
    date: "January, 2025",
  },
];
